project_id = "hmuhmyynazfpqttuurcj"

[functions.get-location]
verify_jwt = false

[functions.fetch-exchange-rates]
verify_jwt = false

[functions.notify-order]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false